### ISSUE TITLE
New release with Sphinx 2+ support

### ISSUE THREAD

**Issue by agjohnson** [sphinx-contrib/autoanysrc#2]
A while back I had added Sphinx >2 support, in #1, and I was curious if there is any possibility of getting a new release out of autoanysrc? I'd love to be able to document use cases that this extension enables. But, I just realized this extension is only installable via git at the moment, unless you're also using an old release of Sphinx. Sphinx 3 has been out for a while, and Sphinx 5 is coming soon. Sphinx users might not know that this package is still usable, as it breaks Sphinx builds for newer versions.

This is a module that I find incredibly useful and I really like using this for reference documentation of otherwise unsupported file types. It fills this gap in tooling quite nicely -- I recommend it to users for documenting odd source files like Terraform and YAML source files.

**Comment by estin** [comment]
Hi! I don't remember any reasons to stay on old sphinx.
This project was for my personal use cases and result was sufficient to publish it as opensource.
And now I don't use it and don't spend time for this project. And I was thinking about autoanysrc as "silver bullet".

I will try to support new sphinx version soon, and may be upload it to pypi.

**Comment by estin** [comment]
please check this release https://pypi.org/project/sphinxcontrib-autoanysrc/

**Comment by agjohnson** [comment]
Awesome, thanks for the quick release!

If you need any help with maintenance or aren't looking to do much more with this project, the RTD core team could definitely help here as well. The one feature we've wanted to contribute here would be easier configuration of the analyzer classes, but otherwise this project already works great for extracting reST from places reST doesn't normally fit.

**Comment by agjohnson** [comment]
Oops, looks like this release pinned Sphinx 2 with the requirement specifier used in the poetry config:
https://github.com/sphinx-contrib/autoanysrc/commit/e3d58020d3c3fde0018243a44158133e2d29bc94#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R27

`^1.6` will select the last release in the `1.x` series, or `1.8.5`:
https://python-poetry.org/docs/dependency-specification/#caret-requirements

This selector should probably be `Sphinx>=1.6`. I'm having trouble getting the configuration to work with Poetry though, so can't test this. The new release will currently throw an error if you try to install with a recent Sphinx install:

```
ERROR: Cannot install Sphinx==4.4.0 and sphinxcontrib-autoanysrc==0.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Sphinx==4.4.0
    sphinxcontrib-autoanysrc 0.1.0 depends on Sphinx<2.0 and >=1.6
```

**Comment by estin** [comment]
And now please try release 0.1.1 )

I can maintain this project (review&release) in my free time.
For me no needs to improve/envolve it, especially for now I use rust lang and markdown (shame for me) for new projects )

If you have some great ideas/features for autoanysrc we can implement it.
I would glade for any ways to make life of this project longer, even delegate to another maintainer(s)

**Comment by agjohnson** [comment]
0.1.1 looks great, I didn't hit the same compatibility issue this time. Thanks again for the new release!

We'll be sure to raise some issues if there is anything major we might want to include, otherwise expect some pull requests!
