### ISSUE TITLE
Support newer versions of Sphinx (5, 6 and 7)

### ISSUE THREAD

**Issue by humitos** [sphinx-contrib/autoanysrc#3]
Hi 👋🏼  and thanks for the extension! ❤️ 

Today I realized this extension requires `Sphinx<5` and the latest Sphinx version is `7.x`. Is there any plan to add support for newer versions of Sphinx? I found myself not being able to upgrade to newer Sphinx versions due to this extension only.

**Comment by estin** [comment]
Hi! I will try to support `Sphinx >= 5` .

It take some time

**Comment by estin** [comment]
release 0.2.0 with Sphinx >= 1.8, < 8.0

actually only tox.ini affected.

**Comment by humitos** [comment]
Wooohooo! Thanks a lot! I was able to upgrade my Sphinx version without issues 💯
